/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    entities: Entity;
    topics: Topic;
    clusters: Cluster;
    contentItems: ContentItem;
    surfaces: Surface;
    signals: Signal;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    entities: EntitiesSelect<false> | EntitiesSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    clusters: ClustersSelect<false> | ClustersSelect<true>;
    contentItems: ContentItemsSelect<false> | ContentItemsSelect<true>;
    surfaces: SurfacesSelect<false> | SurfacesSelect<true>;
    signals: SignalsSelect<false> | SignalsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    socialLinks: SocialLink;
    seoDefaults: SeoDefault;
    brandSystem: BrandSystem;
    'site-identity': SiteIdentity;
    'site-navigation': SiteNavigation;
    'site-contact': SiteContact;
    'site-newsletter': SiteNewsletter;
    'site-homepage': SiteHomepage;
    'site-cta-library': SiteCtaLibrary;
  };
  globalsSelect: {
    socialLinks: SocialLinksSelect<false> | SocialLinksSelect<true>;
    seoDefaults: SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    brandSystem: BrandSystemSelect<false> | BrandSystemSelect<true>;
    'site-identity': SiteIdentitySelect<false> | SiteIdentitySelect<true>;
    'site-navigation': SiteNavigationSelect<false> | SiteNavigationSelect<true>;
    'site-contact': SiteContactSelect<false> | SiteContactSelect<true>;
    'site-newsletter': SiteNewsletterSelect<false> | SiteNewsletterSelect<true>;
    'site-homepage': SiteHomepageSelect<false> | SiteHomepageSelect<true>;
    'site-cta-library': SiteCtaLibrarySelect<false> | SiteCtaLibrarySelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'ai-agent';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Pages for the public BBF site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL slug (auto-generated from title, can be edited)
   */
  slug: string;
  /**
   * Full URL path (auto-computed from slug + parent)
   */
  path?: string | null;
  /**
   * Parent page (for nested URLs)
   */
  parent?: (number | null) | Page;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities".
 */
export interface Entity {
  id: number;
  /**
   * kebab-case, único globalmente (ej. zavala, bbf)
   */
  slug: string;
  kind: 'organization' | 'person' | 'concept' | 'tool' | 'place';
  name: string;
  alternateNames?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  externalIds?: {
    /**
     * QID (ej. Q12345)
     */
    wikidata?: string | null;
    /**
     * schema.org type URL
     */
    schemaOrg?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    github?: string | null;
    crunchbase?: string | null;
  };
  /**
   * URLs externas que apuntan a esta entity (Schema.org sameAs)
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  person?: {
    jobTitle?: string | null;
    worksFor?: (number | null) | Entity;
    alumniOf?: (number | Entity)[] | null;
    knowsAbout?: (number | Topic)[] | null;
    knowsLanguage?:
      | {
          iso: string;
          id?: string | null;
        }[]
      | null;
    homeLocation?: string | null;
    nationality?: string | null;
  };
  organization?: {
    foundingDate?: string | null;
    foundingLocation?: string | null;
    founders?: (number | Entity)[] | null;
    knowsAbout?: (number | Topic)[] | null;
    areaServed?:
      | {
          region: string;
          id?: string | null;
        }[]
      | null;
    contactPoint?:
      | {
          email?: string | null;
          telephone?: string | null;
          /**
           * support, sales, etc.
           */
          type?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  concept?: {
    definition?: string | null;
    /**
     * ej. brand-strategy, ai-systems
     */
    field?: string | null;
    relatedConcepts?: (number | Entity)[] | null;
  };
  tool?: {
    category?: string | null;
    vendor?: (number | null) | Entity;
    homepage?: string | null;
  };
  primaryImage?: (number | null) | Media;
  status: 'active' | 'deprecated';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  slug: string;
  name: string;
  description?: string | null;
  kind: 'concept' | 'tool' | 'sector' | 'method';
  /**
   * null = top-level
   */
  parentTopic?: (number | null) | Topic;
  /**
   * Si el topic ES una entity (ej. concept entity)
   */
  representedBy?: (number | null) | Entity;
  searchKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Q12345 si tiene Wikidata
   */
  wikidataQID?: string | null;
  status: 'active' | 'deprecated';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clusters".
 */
export interface Cluster {
  id: number;
  /**
   * CS-01 | P3 | P3-C2
   */
  code: string;
  slug: string;
  tier: 'cornerstone' | 'pillar' | 'cluster';
  name: string;
  description?: string | null;
  /**
   * pillar → cornerstone; cluster → pillar
   */
  parentCluster?: (number | null) | Cluster;
  topicRefs?:
    | {
        topic: number | Topic;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL slug localizado (ES: cerebro-marca / EN: brand-brain). null para clusters genéricos.
   */
  canonicalSlug?: string | null;
  /**
   * Mínimo de ContentItems para "authority"
   */
  authorityThreshold?: number | null;
  status: 'active' | 'deprecated';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentItems".
 */
export interface ContentItem {
  id: number;
  slug: string;
  kind: 'cornerstone-page' | 'pillar-page' | 'cluster-article' | 'case' | 'episode' | 'page' | 'post';
  /**
   * null para pages no editoriales
   */
  format?: ('F-1' | 'F-2' | 'F-3' | 'F-4' | 'F-5' | 'F-6') | null;
  layer?: ('B' | 'Z-cross') | null;
  clusterRefs?:
    | {
        cluster: number | Cluster;
        role: 'primary' | 'secondary';
        id?: string | null;
      }[]
    | null;
  title: string;
  subtitle?: string | null;
  excerpt: string;
  blocks?:
    | (
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            question: string;
            answer: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            term: string;
            definition: string;
            /**
             * Schema.org DefinedTerm linked to entity
             */
            relatedEntityRef?: (number | null) | Entity;
            id?: string | null;
            blockName?: string | null;
            blockType: 'definition';
          }
        | {
            variant: 'info' | 'warning' | 'success' | 'note';
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            text: string;
            author?: string | null;
            role?: string | null;
            /**
             * Publication, book, or context of the quote
             */
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            /**
             * Optional section label rendered alongside the divider
             */
            label?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
        | {
            text: string;
            href: string;
            variant: 'primary' | 'secondary' | 'ghost';
            external?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * e.g. "87%", "3x", "$2M"
             */
            number: string;
            unit?: string | null;
            label: string;
            /**
             * Source or qualifying context for the claim
             */
            context?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stat';
          }
        | {
            image: number | Media;
            alt: string;
            caption?: string | null;
            lazyLoad?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            video: number | Media;
            poster?: (number | null) | Media;
            caption?: string | null;
            autoplay?: boolean | null;
            loop?: boolean | null;
            muted?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            images: {
              image: number | Media;
              alt: string;
              caption?: string | null;
              id?: string | null;
            }[];
            layout?: ('grid' | 'carousel') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            provider: 'youtube' | 'vimeo' | 'spotify' | 'twitter' | 'other';
            /**
             * Canonical URL of the content to embed
             */
            url: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            language?:
              | ('typescript' | 'javascript' | 'tsx' | 'css' | 'html' | 'json' | 'bash' | 'sql' | 'python' | 'text')
              | null;
            /**
             * Optional filename shown above the code block
             */
            filename?: string | null;
            content: string;
            lineNumbers?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code';
          }
        | {
            title?: string | null;
            columns: {
              label: string;
              /**
               * Visually highlights this column as the recommended option
               */
              highlight?: boolean | null;
              id?: string | null;
            }[];
            rows: {
              feature: string;
              values: {
                /**
                 * Use "✓", "✗", or descriptive text
                 */
                value?: string | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison-table';
          }
        | {
            /**
             * Heading shown above the TOC
             */
            title?: string | null;
            mode?: ('auto' | 'manual') | null;
            /**
             * Required only when mode is manual
             */
            items?:
              | {
                  label: string;
                  /**
                   * ID of the heading element (without #)
                   */
                  anchor: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table-of-contents';
          }
        | {
            /**
             * Raw HTML — sanitized server-side before render. Admins only.
             */
            html: string;
            /**
             * Internal label for identifying this block in the admin UI
             */
            label?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'custom-html';
          }
      )[]
    | null;
  authors: (number | Entity)[];
  contributors?: (number | Entity)[] | null;
  entityMentions?:
    | {
        entity: number | Entity;
        sameAs?: string | null;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  topicRefs?:
    | {
        topic: number | Topic;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  citations?:
    | {
        name: string;
        author: string;
        year?: number | null;
        url?: string | null;
        type: 'academic' | 'industry' | 'primary-source';
        id?: string | null;
      }[]
    | null;
  editorialState?: ('A' | 'B' | 'C' | 'D') | null;
  audits?: {
    aud01_informationGain?: {
      passed?: boolean | null;
      /**
       * Solo para aud01 (information gain)
       */
      score?: number | null;
      note?: string | null;
    };
    aud02_eeat?: {
      passed?: boolean | null;
      /**
       * Solo para aud01 (information gain)
       */
      score?: number | null;
      note?: string | null;
    };
    aud03_geoChecklist?: {
      passed?: boolean | null;
      /**
       * Solo para aud01 (information gain)
       */
      score?: number | null;
      note?: string | null;
    };
    aud04_voiceBbf?: {
      passed?: boolean | null;
      /**
       * Solo para aud01 (information gain)
       */
      score?: number | null;
      note?: string | null;
    };
    aud05_schema?: {
      passed?: boolean | null;
      /**
       * Solo para aud01 (information gain)
       */
      score?: number | null;
      note?: string | null;
    };
    aud06_antipatterns?: {
      passed?: boolean | null;
      /**
       * Solo para aud01 (information gain)
       */
      score?: number | null;
      note?: string | null;
    };
    aud07_copyEdit?: {
      passed?: boolean | null;
      /**
       * Solo para aud01 (information gain)
       */
      score?: number | null;
      note?: string | null;
    };
  };
  publishedAt?: string | null;
  scheduledAt?: string | null;
  aiGenerated?: boolean | null;
  aiModel?: string | null;
  aiPrompt?: string | null;
  /**
   * Computed via beforeChange hook
   */
  canonicalUrl?: string | null;
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Auto-generated. Edit restricted to admin debugging.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surfaces".
 */
export interface Surface {
  id: number;
  slug: string;
  kind:
    | 'web-html'
    | 'json-ld'
    | 'llms-txt'
    | 'llms-full-txt'
    | 'rss'
    | 'open-graph'
    | 'twitter-card'
    | 'sitemap-entry'
    | 'social-atom'
    | 'newsletter-snippet'
    | 'podcast-rss';
  contentItemRef?: (number | null) | ContentItem;
  /**
   * Global this Surface represents. Use instead of contentItemRef for Global-level surfaces.
   */
  globalRef?:
    | (
        | 'site-homepage'
        | 'site-identity'
        | 'socialLinks'
        | 'brandSystem'
        | 'site-navigation'
        | 'seoDefaults'
        | 'site-newsletter'
        | 'site-contact'
      )
    | null;
  locale: 'es' | 'en';
  /**
   * Computed output: HTML string, JSON-LD object, etc.
   */
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generatedAt?: string | null;
  generatorVersion?: string | null;
  status?: ('published' | 'draft' | 'invalid') | null;
  validations?: {
    schemaOrgValid?: boolean | null;
    coreWebVitalsOk?: boolean | null;
    lengthOk?: boolean | null;
    contentParity?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals".
 */
export interface Signal {
  id: number;
  kind:
    | 'page-view'
    | 'scroll-depth'
    | 'cta-click'
    | 'newsletter-signup'
    | 'contact-submission'
    | 'ai-citation'
    | 'backlink'
    | 'social-share'
    | 'newsletter-open'
    | 'podcast-listen';
  contentItemRef?: (number | null) | ContentItem;
  entityRef?: (number | null) | Entity;
  /**
   * Conditional fields per kind (Canon v1 §8.2)
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  capturedFrom: 'ga4' | 'gsc' | 'posthog' | 'promptmonitor' | 'manual' | 'ahrefs';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'entities';
        value: number | Entity;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'clusters';
        value: number | Cluster;
      } | null)
    | ({
        relationTo: 'contentItems';
        value: number | ContentItem;
      } | null)
    | ({
        relationTo: 'surfaces';
        value: number | Surface;
      } | null)
    | ({
        relationTo: 'signals';
        value: number | Signal;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  path?: T;
  parent?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities_select".
 */
export interface EntitiesSelect<T extends boolean = true> {
  slug?: T;
  kind?: T;
  name?: T;
  alternateNames?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  longDescription?: T;
  externalIds?:
    | T
    | {
        wikidata?: T;
        schemaOrg?: T;
        linkedin?: T;
        twitter?: T;
        github?: T;
        crunchbase?: T;
      };
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  person?:
    | T
    | {
        jobTitle?: T;
        worksFor?: T;
        alumniOf?: T;
        knowsAbout?: T;
        knowsLanguage?:
          | T
          | {
              iso?: T;
              id?: T;
            };
        homeLocation?: T;
        nationality?: T;
      };
  organization?:
    | T
    | {
        foundingDate?: T;
        foundingLocation?: T;
        founders?: T;
        knowsAbout?: T;
        areaServed?:
          | T
          | {
              region?: T;
              id?: T;
            };
        contactPoint?:
          | T
          | {
              email?: T;
              telephone?: T;
              type?: T;
              id?: T;
            };
      };
  concept?:
    | T
    | {
        definition?: T;
        field?: T;
        relatedConcepts?: T;
      };
  tool?:
    | T
    | {
        category?: T;
        vendor?: T;
        homepage?: T;
      };
  primaryImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  kind?: T;
  parentTopic?: T;
  representedBy?: T;
  searchKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  wikidataQID?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clusters_select".
 */
export interface ClustersSelect<T extends boolean = true> {
  code?: T;
  slug?: T;
  tier?: T;
  name?: T;
  description?: T;
  parentCluster?: T;
  topicRefs?:
    | T
    | {
        topic?: T;
        weight?: T;
        id?: T;
      };
  canonicalSlug?: T;
  authorityThreshold?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentItems_select".
 */
export interface ContentItemsSelect<T extends boolean = true> {
  slug?: T;
  kind?: T;
  format?: T;
  layer?: T;
  clusterRefs?:
    | T
    | {
        cluster?: T;
        role?: T;
        id?: T;
      };
  title?: T;
  subtitle?: T;
  excerpt?: T;
  blocks?:
    | T
    | {
        'rich-text'?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
              blockName?: T;
            };
        definition?:
          | T
          | {
              term?: T;
              definition?: T;
              relatedEntityRef?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              variant?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              role?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              label?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              text?: T;
              href?: T;
              variant?: T;
              external?: T;
              id?: T;
              blockName?: T;
            };
        stat?:
          | T
          | {
              number?: T;
              unit?: T;
              label?: T;
              context?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              lazyLoad?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              poster?: T;
              caption?: T;
              autoplay?: T;
              loop?: T;
              muted?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              provider?: T;
              url?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        code?:
          | T
          | {
              language?: T;
              filename?: T;
              content?: T;
              lineNumbers?: T;
              id?: T;
              blockName?: T;
            };
        'comparison-table'?:
          | T
          | {
              title?: T;
              columns?:
                | T
                | {
                    label?: T;
                    highlight?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    feature?: T;
                    values?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'table-of-contents'?:
          | T
          | {
              title?: T;
              mode?: T;
              items?:
                | T
                | {
                    label?: T;
                    anchor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'custom-html'?:
          | T
          | {
              html?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  authors?: T;
  contributors?: T;
  entityMentions?:
    | T
    | {
        entity?: T;
        sameAs?: T;
        weight?: T;
        id?: T;
      };
  topicRefs?:
    | T
    | {
        topic?: T;
        weight?: T;
        id?: T;
      };
  citations?:
    | T
    | {
        name?: T;
        author?: T;
        year?: T;
        url?: T;
        type?: T;
        id?: T;
      };
  editorialState?: T;
  audits?:
    | T
    | {
        aud01_informationGain?:
          | T
          | {
              passed?: T;
              score?: T;
              note?: T;
            };
        aud02_eeat?:
          | T
          | {
              passed?: T;
              score?: T;
              note?: T;
            };
        aud03_geoChecklist?:
          | T
          | {
              passed?: T;
              score?: T;
              note?: T;
            };
        aud04_voiceBbf?:
          | T
          | {
              passed?: T;
              score?: T;
              note?: T;
            };
        aud05_schema?:
          | T
          | {
              passed?: T;
              score?: T;
              note?: T;
            };
        aud06_antipatterns?:
          | T
          | {
              passed?: T;
              score?: T;
              note?: T;
            };
        aud07_copyEdit?:
          | T
          | {
              passed?: T;
              score?: T;
              note?: T;
            };
      };
  publishedAt?: T;
  scheduledAt?: T;
  aiGenerated?: T;
  aiModel?: T;
  aiPrompt?: T;
  canonicalUrl?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surfaces_select".
 */
export interface SurfacesSelect<T extends boolean = true> {
  slug?: T;
  kind?: T;
  contentItemRef?: T;
  globalRef?: T;
  locale?: T;
  output?: T;
  generatedAt?: T;
  generatorVersion?: T;
  status?: T;
  validations?:
    | T
    | {
        schemaOrgValid?: T;
        coreWebVitalsOk?: T;
        lengthOk?: T;
        contentParity?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals_select".
 */
export interface SignalsSelect<T extends boolean = true> {
  kind?: T;
  contentItemRef?: T;
  entityRef?: T;
  data?: T;
  occurredAt?: T;
  capturedFrom?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialLinks".
 */
export interface SocialLink {
  id: number;
  linkedin?: string | null;
  twitter?: string | null;
  github?: string | null;
  youtube?: string | null;
  instagram?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults".
 */
export interface SeoDefault {
  id: number;
  defaultTitle?: string | null;
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  twitterHandle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandSystem".
 */
export interface BrandSystem {
  id: number;
  colors?: {
    primaryPalette?: ('red' | 'blue') | null;
    themeMode?: ('light' | 'dark' | 'auto') | null;
  };
  typography?: {
    displayFamily?: ('inter' | 'custom') | null;
    bodyFamily?: ('mulish' | 'custom') | null;
  };
  brand?: {
    logoVariant?: ('icon' | 'horizontal' | 'name-only' | 'stamp') | null;
    accentGradient?: ('red-animated' | 'blue-animated' | 'none') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Canonical brand identity. ONE source of truth for name, domain, founder, schema, content interpolation. Editing here propagates everywhere (metadata, Schema.org, llms.txt, sitemap, {{siteName}} in content).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity".
 */
export interface SiteIdentity {
  id: number;
  /**
   * Nombre canónico de la marca. Aparece en title, OG, Schema, wordmark, llms.txt. Placeholder: {{siteName}}
   */
  siteName: string;
  /**
   * Versión corta para mobile/PWA manifest. Default igual al name si no aplica. Placeholder: {{siteShortName}}
   */
  siteShortName: string;
  /**
   * URL canónica con protocolo. Sin trailing slash. Placeholder: {{siteDomain}}
   */
  siteDomain: string;
  /**
   * Tagline corto para meta description fallback + Schema description. Placeholder: {{siteTagline}}
   */
  siteTagline: string;
  /**
   * Descripción media (150-300 chars). Meta description + OG + Schema. Placeholder: {{siteDescription}}
   */
  siteDescription: string;
  /**
   * Descripción larga para about page y Schema.org Organization.description completa. Placeholder: {{longDescription}}
   */
  longDescription?: string | null;
  /**
   * Format YYYY-MM or YYYY-MM-DD (Schema.org Organization.foundingDate). E.g. 2025-10
   */
  foundingDate?: string | null;
  /**
   * Geographies Sivar Brains serves (Schema.org Organization.areaServed)
   */
  areaServed?:
    | {
        type: 'Country' | 'AdministrativeArea' | 'Region' | 'Place';
        name: string;
        /**
         * ISO 3166-1 alpha-2 (e.g. SV, US, MX)
         */
        iso2?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Co-fundadores de la organización. Schema.org Person array. Multi-founder amplifica entity signal AEO/LLMO 2026 (Knowledge Panel + AI citations). El primer founder (índice 0) alimenta {{founderName}}. Todos alimentan {{foundersList}}.
   */
  founders: {
    /**
     * Nombre completo del co-fundador. Aparece en Schema.org Person.name.
     */
    name: string;
    /**
     * Rol por habilidades — NO títulos corporativos. Ej: "Co-fundador · Arquitecto del método". Schema.org Person.jobTitle.
     */
    role?: string | null;
    /**
     * Entity-home del founder (página personal, portafolio, o LinkedIn). Schema.org Person.url.
     */
    url?: string | null;
    /**
     * URL LinkedIn del founder. Schema.org Person.sameAs.
     */
    linkedin?: string | null;
    /**
     * Organización aliada. Ej: "Brand Brain Foundry" o "Sivar Films". Schema.org Person.affiliation.name.
     */
    affiliation?: string | null;
    id?: string | null;
  }[];
  /**
   * La foundry que construye el sistema. Solo aparece en Schema.org para entity disambiguation.
   */
  producer?: {
    /**
     * Placeholder: {{producerName}}
     */
    name?: string | null;
    url?: string | null;
  };
  seo?: {
    /**
     * Locale OG primario (og:locale).
     */
    defaultLocale?: ('es_SV' | 'es' | 'en_US') | null;
    /**
     * Handle Twitter/X con @. Vacío si no aplica.
     */
    twitterHandle?: string | null;
    /**
     * Path relativo a la imagen OG default (1200x630).
     */
    ogImagePath?: string | null;
    /**
     * Color para manifest + meta theme-color. Hex.
     */
    themeColor?: string | null;
  };
  /**
   * Banner de estado visible en nav (ej: "Beta", "Lanzamiento próximo"). Consumer: Header organism.
   */
  statusBanner?: {
    /**
     * Mostrar u ocultar el banner en Nav.
     */
    enabled?: boolean | null;
    /**
     * Texto del pill de estado.
     */
    label?: string | null;
    /**
     * URL opcional al hacer click en el banner.
     */
    href?: string | null;
    /**
     * Color hex del dot indicador.
     */
    dotColor?: string | null;
  };
  /**
   * Canonical organization entity (D-ALIGN-42). Links to Entities collection. Powers StructuredData JSON-LD. Only organization-type entities shown.
   */
  organizationEntity?: (number | null) | Entity;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Navigation structure: header + footer links. Source of truth for navegación.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation".
 */
export interface SiteNavigation {
  id: number;
  headerLinks?:
    | {
        label: string;
        /**
         * Destino agnóstico: elegí routeKey (ruta canónica) o page (página dinámica). SSOT, sin texto libre.
         */
        linkTarget?: {
          /**
           * Ruta canónica (SSOT routing.ts pathnames). Usar para cornerstones / rutas fijas.
           */
          routeKey?: ('/' | '/cerebro-marca' | '/metodo' | '/casos' | '/contacto' | '/quienes-somos' | '/blog') | null;
          /**
           * Página dinámica (alternativa a routeKey). Dormido hasta que existan Pages.
           */
          page?: (number | null) | Page;
        };
        /**
         * Si está activo, al hacer hover/click se abre mega-menu con sub-links.
         */
        hasSubMenu?: boolean | null;
        /**
         * Sub-links del mega-menu (visibles al hacer hover/click en desktop).
         */
        subLinks?:
          | {
              label: string;
              /**
               * Destino agnóstico: page (página hija) o external (URL externa). Anchors → 4.C.3.
               */
              linkTarget?: {
                /**
                 * Página hija (D-NAV-9). href deriva de page.path (SSOT).
                 */
                page?: (number | null) | Page;
                /**
                 * URL externa cruda (escape hatch, sin SSOT). Solo links fuera del sitio.
                 */
                external?: string | null;
              };
              /**
               * Descripción corta opcional (ej: "El proceso paso a paso").
               */
              description?: string | null;
              mediaType: 'none' | 'image' | 'video';
              /**
               * Imagen o video preview (solo si mediaType ≠ none).
               */
              media?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * CTA destacado en header (D-BBF-KB-100). Junto a LanguageSwitcher.
   */
  headerCta: {
    /**
     * Key del CTA en SiteCtaLibrary (D-NAV-11). Label e intent vienen del catálogo.
     */
    ctaKey: string;
    /**
     * Destino agnóstico: elegí routeKey (ruta canónica) o page (página dinámica). SSOT, sin texto libre.
     */
    linkTarget?: {
      /**
       * Ruta canónica (SSOT routing.ts pathnames). Usar para cornerstones / rutas fijas.
       */
      routeKey?: ('/' | '/cerebro-marca' | '/metodo' | '/casos' | '/contacto' | '/quienes-somos' | '/blog') | null;
      /**
       * Página dinámica (alternativa a routeKey). Dormido hasta que existan Pages.
       */
      page?: (number | null) | Page;
    };
  };
  /**
   * Footer link groups (e.g. Navigation, Resources, Company)
   */
  footerGroups?:
    | {
        /**
         * Title of the group (e.g. "Navigation"). Shown in uppercase canon.
         */
        groupTitle: string;
        links?:
          | {
              label: string;
              /**
               * Destino agnóstico: elegí routeKey (ruta canónica) o page (página dinámica). SSOT, sin texto libre.
               */
              linkTarget?: {
                /**
                 * Ruta canónica (SSOT routing.ts pathnames). Usar para cornerstones / rutas fijas.
                 */
                routeKey?:
                  | ('/' | '/cerebro-marca' | '/metodo' | '/casos' | '/contacto' | '/quienes-somos' | '/blog')
                  | null;
                /**
                 * Página dinámica (alternativa a routeKey). Dormido hasta que existan Pages.
                 */
                page?: (number | null) | Page;
              };
              /**
               * Optional badge text (e.g. "New", "Beta", "Soon"). Empty = no badge.
               */
              flag?: string | null;
              /**
               * Badge color variant (visible only if flag has text).
               */
              flagVariant?: ('default' | 'accent' | 'success' | 'beta') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact metadata (NOT rendered as mailto in front per D-BBF-KB-99). Used for: JSON-LD Schema.org, contact form recipient, admin reference.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contact".
 */
export interface SiteContact {
  id: number;
  /**
   * Email principal (recipient form contacto). NO renderizado en front.
   */
  primaryEmail: string;
  /**
   * Email fallback solo para mensajes de error técnico interno.
   */
  fallbackEmail?: string | null;
  /**
   * Email FROM para envíos transaccionales (Resend domain verified).
   */
  fromEmail: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Newsletter subscription content (D-BBF-KB-103). Copy editable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-newsletter".
 */
export interface SiteNewsletter {
  id: number;
  /**
   * Habilita o deshabilita newsletter site-wide.
   */
  enabled?: boolean | null;
  /**
   * Título principal newsletter box (footer).
   */
  title: string;
  /**
   * Descripción corta value prop (max 200 chars).
   */
  description: string;
  emailPlaceholder?: string | null;
  submitLabel: string;
  submittingLabel?: string | null;
  successTitle?: string | null;
  successMessage?: string | null;
  /**
   * Nota privacidad debajo del input (microcopy canon).
   */
  privacyNote?: string | null;
  confirmationEmailSubject: string;
  confirmationEmailBody: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage content: hero, capabilities, method, process. Single source of truth (W-2).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-homepage".
 */
export interface SiteHomepage {
  id: number;
  hero: {
    /**
     * Primera línea del H1 principal (color primario).
     */
    h1Line1: string;
    /**
     * Segunda línea del H1 (tono suave / muted).
     */
    h1Line2Soft: string;
    /**
     * Párrafo principal bajo el H1 (max 280 chars).
     */
    ledeBody: string;
    /**
     * Frase de énfasis al final del lede (peso 500, color primario).
     */
    ledeEmphasis: string;
    ctaPrimary: {
      /**
       * Texto del botón primario.
       */
      label: string;
      /**
       * URL o anchor destino.
       */
      href: string;
    };
    ctaSecondary: {
      /**
       * Texto del botón secundario (ghost).
       */
      label: string;
      /**
       * URL o anchor destino.
       */
      href: string;
    };
    media: {
      /**
       * Etiqueta decorativa del chrome superior del frame (sintético, hardcoded canon).
       */
      chromeLabel?: string | null;
      /**
       * Imagen poster del video (se muestra antes de carga).
       */
      videoPoster?: (number | null) | Media;
      /**
       * Fuentes de video en orden de prioridad (mejor codec primero).
       */
      videoSources?:
        | {
            /**
             * Path relativo o URL del archivo de video.
             */
            src: string;
            /**
             * Codec / contenedor del video.
             */
            type: 'webm-av1' | 'webm-vp9' | 'mp4-h264' | 'mp4-h265' | 'mp4-av1' | 'mov';
            id?: string | null;
          }[]
        | null;
      /**
       * Etiqueta del tipo de demostración (muted, bajo el video).
       */
      demoLabel: string;
      /**
       * Descripción de la demo visible en el footer del frame.
       */
      footCaption: string;
    };
    /**
     * Items del ticker marquee decorativo (min 4, max 12). Se duplican automáticamente para el loop.
     */
    ticker?:
      | {
          /**
           * Texto del item (ej: "WhatsApp Business · activo").
           */
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  capabilities: {
    /**
     * Eyebrow label sobre el H2 (ej: §2 · Capacidades).
     */
    eyebrow?: string | null;
    /**
     * Primera línea del H2 de sección (color primario).
     */
    h2Line1: string;
    /**
     * Segunda línea del H2 (tono muted).
     */
    h2Line2Soft: string;
    /**
     * Párrafo introductorio de la sección (max ~200 chars).
     */
    lead: string;
    /**
     * 5 spokes del Hub MEMORIA (orden = ángulo 0°→72°→144°→216°→288°). Defaults: Conversa/Genera/Automatiza/Integra/Aprende.
     */
    hubSpokes?:
      | {
          /**
           * Nombre del spoke (ej: Conversa). Uppercase automático en UI.
           */
          name: string;
          /**
           * Sub-labels del spoke (ej: WhatsApp · Web · Voz).
           */
          meta?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Las 5 capacidades BBF (orden = orden visual). Exactamente 5.
     */
    items?:
      | {
          /**
           * Identificador único: conversa | genera | automatiza | integra | aprende
           */
          slug: string;
          /**
           * Nombre de la capacidad (ej: Conversa).
           */
          title: string;
          /**
           * Frase de impacto (1-2 líneas, peso medio).
           */
          lede: string;
          /**
           * Descripción desarrollada (2-3 párrafos breves).
           */
          body: string;
          /**
           * Lista de características clave (3-5 items).
           */
          bullets?:
            | {
                /**
                 * Texto del bullet.
                 */
                text: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Ejemplo concreto de uso (1-2 líneas, blockquote).
           */
          example: string;
          scene: {
            /**
             * Tipo de visualización para esta capacidad.
             */
            kind: 'chat' | 'pipeline' | 'workflow' | 'stack' | 'media';
            /**
             * Metadato contextual del scene (ej: "WhatsApp · Web · Voz").
             */
            meta: string;
            chat?: {
              messages?:
                | {
                    who: 'user' | 'brain';
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Texto decorativo del footer del scene.
               */
              footer?: string | null;
            };
            pipeline?: {
              steps?:
                | {
                    /**
                     * Nombre del paso.
                     */
                    label: string;
                    /**
                     * Detalle secundario del paso.
                     */
                    detail: string;
                    state: 'done' | 'live' | 'queue';
                    id?: string | null;
                  }[]
                | null;
              /**
               * Texto decorativo del footer del scene.
               */
              footer?: string | null;
            };
            workflow?: {
              nodes?:
                | {
                    x: number;
                    y: number;
                    label: string;
                    kind: 'in' | 'step' | 'branch' | 'auto' | 'human';
                    id?: string | null;
                  }[]
                | null;
              edges?:
                | {
                    from: number;
                    to: number;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Texto decorativo del footer del scene.
               */
              footer?: string | null;
            };
            stack?: {
              groups?:
                | {
                    /**
                     * Nombre del grupo de tecnologías.
                     */
                    label: string;
                    items?:
                      | {
                          /**
                           * Nombre del item/tecnología.
                           */
                          name: string;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Texto decorativo del footer del scene.
               */
              footer?: string | null;
            };
            media?: {
              mediaType: 'image' | 'video';
              /**
               * Imagen portrait 9:16 o video portrait 9:16.
               */
              asset: number | Media;
              /**
               * Frame poster del video (opcional).
               */
              posterFallback?: (number | null) | Media;
              /**
               * Pie de imagen/video opcional.
               */
              caption?: string | null;
              /**
               * Lissajous deco opcional. 6 variantes 2D.
               */
              lissajousVariant?:
                | (
                    | 'trefoil-2d'
                    | 'pretzel-2d'
                    | 'wave-2d'
                    | 'ring-2d'
                    | 'dense-2d'
                    | 'figure8-2d'
                    | 'process-2d'
                    | 'case-2d'
                    | 'comparison-2d'
                    | 'cross-2d'
                    | 'metodo-2d'
                  )
                | null;
              /**
               * Texto decorativo del footer del scene.
               */
              footer?: string | null;
            };
          };
          id?: string | null;
        }[]
      | null;
  };
  caseStudy?: {
    /**
     * Eyebrow mono label (ej: §3 · CASO).
     */
    eyebrow?: string | null;
    /**
     * Primera línea del H2 (color texto dark principal).
     */
    h2Line1?: string | null;
    /**
     * Segunda línea del H2 (gradient blue animado).
     */
    h2Line2Soft?: string | null;
    /**
     * Párrafo introductorio bajo el H2 (max ~220 chars).
     */
    lead?: string | null;
    /**
     * Etiqueta mono del chrome del frame (ej: SIVAR-BRAINS · WhatsApp Business · live).
     */
    mediaChromeLabel?: string | null;
    /**
     * Timestamp decorativo del chrome (ej: captura · 23:04 viernes).
     */
    mediaTimestamp?: string | null;
    /**
     * Imagen estática 16:9 del caso. Si se prefiere video, usar videoPoster + videoSources.
     */
    mediaAsset?: (number | null) | Media;
    /**
     * Imagen poster del video del caso (mostrada antes de carga). Opcional.
     */
    videoPoster?: (number | null) | Media;
    /**
     * Fuentes de video del caso en orden de prioridad (mejor codec primero). Vacío → placeholder.
     */
    videoSources?:
      | {
          /**
           * URL del archivo de video.
           */
          src: string;
          /**
           * Codec / contenedor del video.
           */
          type: 'webm-av1' | 'webm-vp9' | 'mp4-h264' | 'mp4-h265' | 'mp4-av1' | 'mov';
          id?: string | null;
        }[]
      | null;
    /**
     * Las 3 fases del caso (Situación→Construcción→Operación). Exactamente 3.
     */
    phases?:
      | {
          /**
           * Tag temporal del phase (ej: Antes, 12 semanas, Hoy).
           */
          tag: string;
          /**
           * Título de la fase (ej: Situación, Construcción, Operación).
           */
          title: string;
          /**
           * Descripción de la fase (2-3 líneas).
           */
          body: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Texto de la cita blockquote (display font grande).
     */
    quoteText?: string | null;
    /**
     * Atribución de la cita (mono-xs, ej: — Equipo BBF · Sivar Brains).
     */
    quoteCaption?: string | null;
    /**
     * Label del CTA link-arrow (ej: Leer el caso completo).
     */
    ctaLabel?: string | null;
    /**
     * URL destino del CTA.
     */
    ctaHref?: string | null;
  };
  /**
   * §4 comparison table: Why a brand brain vs agencies / consultants / SaaS.
   */
  comparison?: {
    /**
     * Eyebrow label (ej: §4 · POR QUÉ).
     */
    eyebrow?: string | null;
    /**
     * Primera línea del H2 (color primario).
     */
    h2Line1?: string | null;
    /**
     * Segunda línea del H2 (tono muted).
     */
    h2Line2Soft?: string | null;
    /**
     * Párrafo introductorio bajo el H2 (max ~220 chars).
     */
    lead?: string | null;
    /**
     * Columnas de la tabla comparativa. Exactamente 1 columna debe tener isHighlighted=true (columna BBF).
     */
    columns?:
      | {
          /**
           * Nombre de la columna (ej: Cerebro de marca).
           */
          label: string;
          /**
           * Sub-label de la columna (ej: Sistema propio).
           */
          sub?: string | null;
          /**
           * Columna BBF destacada. Activa el crown pill "▼ BBF" y es el tab por defecto en mobile.
           */
          isHighlighted?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Filas de la tabla comparativa (dimensiones de comparación).
     */
    rows?:
      | {
          /**
           * Nombre de la dimensión (ej: Aprende tu empresa).
           */
          attribute: string;
          /**
           * Una celda por columna, en el mismo orden que las columnas definidas arriba.
           */
          cells?:
            | {
                /**
                 * Ícono de la celda (yes=✓ circulo, no=✗ circulo, mid=— circulo, text=solo texto).
                 */
                state: 'yes' | 'no' | 'mid' | 'text';
                /**
                 * Texto de la celda.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    epilogue?: {
      /**
       * Título del epílogo (ej: La diferencia operativa).
       */
      title?: string | null;
      /**
       * Párrafos del epílogo separados por línea en blanco. Se renderizan como párrafos independientes.
       */
      body?: string | null;
    };
  };
  /**
   * §5 three coordinated services: Diagnóstico → Build → Retainer.
   */
  method?: {
    /**
     * Eyebrow label (ej: §5 · MÉTODO).
     */
    eyebrow?: string | null;
    /**
     * Primera línea del H2 (ej: Tres servicios coordinados.).
     */
    h2Line1?: string | null;
    /**
     * Segunda línea del H2 en tono muted (ej: Sin sorpresas.).
     */
    h2Line2Soft?: string | null;
    /**
     * Nodos del process bar horizontal (01 · Diagnóstico, etc.).
     */
    phases?:
      | {
          /**
           * Número del nodo (ej: 01).
           */
          number: string;
          /**
           * Etiqueta corta del nodo (ej: Diagnóstico).
           */
          shortLabel: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Los 3 servicios BBF (Diagnóstico / Build / Retainer). Exactamente 3.
     */
    services?:
      | {
          /**
           * Número del servicio (ej: 01).
           */
          number: string;
          /**
           * Nombre del servicio (ej: Diagnóstico).
           */
          name: string;
          /**
           * Duración (ej: 2 – 3 semanas).
           */
          duration?: string | null;
          /**
           * Compromiso (ej: Alcance cerrado · sin recurrencia).
           */
          commitment?: string | null;
          /**
           * Descripción del servicio (2-3 líneas).
           */
          body?: string | null;
          /**
           * Lista de entregables del servicio (3-4 items).
           */
          deliverables?:
            | {
                /**
                 * Texto del entregable.
                 */
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Texto principal del quote (ej: No hay urgencia.).
     */
    quoteText?: string | null;
    /**
     * Segunda línea del quote en tono soft (ej: Hay método.).
     */
    quoteTextSoft?: string | null;
    /**
     * Atribución del quote (ej: Canon BBF · 01).
     */
    quoteAttribution?: string | null;
    /**
     * Texto del CTA link-arrow (ej: Conocer el método completo).
     */
    ctaLabel?: string | null;
    /**
     * URL destino del CTA.
     */
    ctaHref?: string | null;
  };
  /**
   * §6 last homepage section. Dark surface. Statement + main CTA + brand signature.
   */
  closing?: {
    /**
     * Eyebrow meta row izquierda (ej: §6 · CIERRE).
     */
    eyebrow?: string | null;
    /**
     * Nombre de marca en la meta row (asset fijo — editable por seguridad).
     */
    brandLine?: string | null;
    /**
     * Año en la meta row. Si vacío → fallback dinámico new Date().getFullYear().
     */
    brandYear?: string | null;
    /**
     * Primera línea del statement H2 display (color primario sobre dark).
     */
    statementLine1?: string | null;
    /**
     * Segunda línea del statement H2 (red gradient animado — D-S6-06).
     */
    statementLine2Soft?: string | null;
    cta?: {
      /**
       * Texto del CTA principal (ej: Sentémonos a pensar).
       */
      label?: string | null;
      /**
       * URL destino del CTA.
       */
      href?: string | null;
    };
    /**
     * Nota bajo el CTA (ej: Diagnóstico cerrado · 2-3 semanas · sin compromiso).
     */
    ctaNote?: string | null;
    /**
     * Tagline de la firma brand en pill (ej: No hay urgencia. Hay método.).
     */
    signatureTagline?: string | null;
  };
  /**
   * GEO Answer Capsules for AI citation (Perplexity, ChatGPT, Claude). One 40-60-word capsule per homepage section, ES + EN. Fill after TP-SEO-01 sign-off.
   */
  seo?: {
    /**
     * One capsule per homepage section (§1 Hero, §2 Capabilities, §3 Case, §4 Why, §5 Method). Fill ES + EN for each. 40-60 words each.
     */
    answerCapsules?:
      | {
          /**
           * Sección del homepage a la que responde esta cápsula.
           */
          sectionId: 'hero' | 'capabilities' | 'caseStudy' | 'comparison' | 'method';
          /**
           * Texto de citación IA: responde directamente la pregunta implícita de la sección. 40-60 palabras. Sin filler. Sin marca registrada.
           */
          capsule: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Single source of truth for all cross-site CTA labels and styles (D-DS-18, D-NAV-11).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-cta-library".
 */
export interface SiteCtaLibrary {
  id: number;
  items?:
    | {
        /**
         * Identificador único (e.g. "watch-it-run"). Usado como ctaKey en nav y consumers.
         */
        key: string;
        label: string;
        type: 'solid' | 'outline';
        intent: 'primary' | 'secondary' | 'black' | 'red';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialLinks_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  linkedin?: T;
  twitter?: T;
  github?: T;
  youtube?: T;
  instagram?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  twitterHandle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandSystem_select".
 */
export interface BrandSystemSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        primaryPalette?: T;
        themeMode?: T;
      };
  typography?:
    | T
    | {
        displayFamily?: T;
        bodyFamily?: T;
      };
  brand?:
    | T
    | {
        logoVariant?: T;
        accentGradient?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity_select".
 */
export interface SiteIdentitySelect<T extends boolean = true> {
  siteName?: T;
  siteShortName?: T;
  siteDomain?: T;
  siteTagline?: T;
  siteDescription?: T;
  longDescription?: T;
  foundingDate?: T;
  areaServed?:
    | T
    | {
        type?: T;
        name?: T;
        iso2?: T;
        id?: T;
      };
  founders?:
    | T
    | {
        name?: T;
        role?: T;
        url?: T;
        linkedin?: T;
        affiliation?: T;
        id?: T;
      };
  producer?:
    | T
    | {
        name?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        defaultLocale?: T;
        twitterHandle?: T;
        ogImagePath?: T;
        themeColor?: T;
      };
  statusBanner?:
    | T
    | {
        enabled?: T;
        label?: T;
        href?: T;
        dotColor?: T;
      };
  organizationEntity?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation_select".
 */
export interface SiteNavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        linkTarget?:
          | T
          | {
              routeKey?: T;
              page?: T;
            };
        hasSubMenu?: T;
        subLinks?:
          | T
          | {
              label?: T;
              linkTarget?:
                | T
                | {
                    page?: T;
                    external?: T;
                  };
              description?: T;
              mediaType?: T;
              media?: T;
              id?: T;
            };
        id?: T;
      };
  headerCta?:
    | T
    | {
        ctaKey?: T;
        linkTarget?:
          | T
          | {
              routeKey?: T;
              page?: T;
            };
      };
  footerGroups?:
    | T
    | {
        groupTitle?: T;
        links?:
          | T
          | {
              label?: T;
              linkTarget?:
                | T
                | {
                    routeKey?: T;
                    page?: T;
                  };
              flag?: T;
              flagVariant?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contact_select".
 */
export interface SiteContactSelect<T extends boolean = true> {
  primaryEmail?: T;
  fallbackEmail?: T;
  fromEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-newsletter_select".
 */
export interface SiteNewsletterSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  description?: T;
  emailPlaceholder?: T;
  submitLabel?: T;
  submittingLabel?: T;
  successTitle?: T;
  successMessage?: T;
  privacyNote?: T;
  confirmationEmailSubject?: T;
  confirmationEmailBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-homepage_select".
 */
export interface SiteHomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        h1Line1?: T;
        h1Line2Soft?: T;
        ledeBody?: T;
        ledeEmphasis?: T;
        ctaPrimary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        media?:
          | T
          | {
              chromeLabel?: T;
              videoPoster?: T;
              videoSources?:
                | T
                | {
                    src?: T;
                    type?: T;
                    id?: T;
                  };
              demoLabel?: T;
              footCaption?: T;
            };
        ticker?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  capabilities?:
    | T
    | {
        eyebrow?: T;
        h2Line1?: T;
        h2Line2Soft?: T;
        lead?: T;
        hubSpokes?:
          | T
          | {
              name?: T;
              meta?: T;
              id?: T;
            };
        items?:
          | T
          | {
              slug?: T;
              title?: T;
              lede?: T;
              body?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              example?: T;
              scene?:
                | T
                | {
                    kind?: T;
                    meta?: T;
                    chat?:
                      | T
                      | {
                          messages?:
                            | T
                            | {
                                who?: T;
                                text?: T;
                                id?: T;
                              };
                          footer?: T;
                        };
                    pipeline?:
                      | T
                      | {
                          steps?:
                            | T
                            | {
                                label?: T;
                                detail?: T;
                                state?: T;
                                id?: T;
                              };
                          footer?: T;
                        };
                    workflow?:
                      | T
                      | {
                          nodes?:
                            | T
                            | {
                                x?: T;
                                y?: T;
                                label?: T;
                                kind?: T;
                                id?: T;
                              };
                          edges?:
                            | T
                            | {
                                from?: T;
                                to?: T;
                                id?: T;
                              };
                          footer?: T;
                        };
                    stack?:
                      | T
                      | {
                          groups?:
                            | T
                            | {
                                label?: T;
                                items?:
                                  | T
                                  | {
                                      name?: T;
                                      id?: T;
                                    };
                                id?: T;
                              };
                          footer?: T;
                        };
                    media?:
                      | T
                      | {
                          mediaType?: T;
                          asset?: T;
                          posterFallback?: T;
                          caption?: T;
                          lissajousVariant?: T;
                          footer?: T;
                        };
                  };
              id?: T;
            };
      };
  caseStudy?:
    | T
    | {
        eyebrow?: T;
        h2Line1?: T;
        h2Line2Soft?: T;
        lead?: T;
        mediaChromeLabel?: T;
        mediaTimestamp?: T;
        mediaAsset?: T;
        videoPoster?: T;
        videoSources?:
          | T
          | {
              src?: T;
              type?: T;
              id?: T;
            };
        phases?:
          | T
          | {
              tag?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        quoteText?: T;
        quoteCaption?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  comparison?:
    | T
    | {
        eyebrow?: T;
        h2Line1?: T;
        h2Line2Soft?: T;
        lead?: T;
        columns?:
          | T
          | {
              label?: T;
              sub?: T;
              isHighlighted?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              attribute?: T;
              cells?:
                | T
                | {
                    state?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        epilogue?:
          | T
          | {
              title?: T;
              body?: T;
            };
      };
  method?:
    | T
    | {
        eyebrow?: T;
        h2Line1?: T;
        h2Line2Soft?: T;
        phases?:
          | T
          | {
              number?: T;
              shortLabel?: T;
              id?: T;
            };
        services?:
          | T
          | {
              number?: T;
              name?: T;
              duration?: T;
              commitment?: T;
              body?: T;
              deliverables?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        quoteText?: T;
        quoteTextSoft?: T;
        quoteAttribution?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        brandLine?: T;
        brandYear?: T;
        statementLine1?: T;
        statementLine2Soft?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        ctaNote?: T;
        signatureTagline?: T;
      };
  seo?:
    | T
    | {
        answerCapsules?:
          | T
          | {
              sectionId?: T;
              capsule?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-cta-library_select".
 */
export interface SiteCtaLibrarySelect<T extends boolean = true> {
  items?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        intent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'contentItems';
      value: number | ContentItem;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}